### ISSUE TITLE
Reduce Size

### ISSUE THREAD

**Issue by akirk** [Automattic/chatrix#158]
Right now the build is just over 6MB. Most of this comes from the directory `build/iframe/assets`

```
du build/iframe/assets
1.9M    *.woff2
2.5M    *.woff
240K    *.svg
36K     *.png
8.0K    *.json
992K    *.js
5.9M	total
```

So the size comes from all the font files. Are they necessary (like are special icons needed) or could we do without them?

**Comment by psrpinto** [comment]
@ashfame and I looked into this. The reason there are both `.woff` and `.woff2` files is for compatibility with older browsers (IE), but both aren't actually loaded by the browser, for most users only the `.woff2` file is loaded.

A complete page load takes 1.1 MB transferred (1.7 uncompressed), of which 422KB are fonts, which proves only needed fonts are being loaded.

Additionally, removing the `.woff` files from the build artifacts would require duplicating hydrogen's `theme.css` in chatrix, which we'd rather not do.

**Comment by ashfame** [comment]
-> #185
