### ISSUE TITLE
My homeserver has a none valid URL.

### ISSUE THREAD

**Issue by Xen01r** [Automattic/chatrix#183]
Hi,

I set up a personal matrix server but I could not use it with chatrix.
In `Settings>Chatrix` when I enter the URL in `Homeserver `it gave me the following error.

`https://myhomeserver:8008/ is not a valid homeserver URL.`

Yet, it works perfectly fine with other clients, like Element (Web, Desktop & mobile).

I though I could bypass this problem using `chatrix_instances` but I did not understand how to use it on my Wordpress.

**Comment by ashfame** [comment]
Hi, Thanks for the bug report!
I confirm that I can reproduce this issue. Will fix it shortly!
