### ISSUE TITLE
In single-room mode, refreshing the page always sends user to session picker

### ISSUE THREAD

**Issue by psrpinto** [Automattic/chatrix#200]
Since https://github.com/Automattic/chatrix/pull/193, when single-room mode is enabled, and user has multiple sessions, chatrix no longer remembers the screen the user was on, and always sends them to session-picker.

This happens in one (or both) of the following scenarios:

1. User first logs in as guest, and then as a "normal" account, since the guest session remains available.
2. User signs in to multiple "normal" accounts.

**Comment by ashfame** [comment]
I suppose we should log out of the guest session as soon as a login is successful.
