### ISSUE TITLE
Retrieve authentication methods from the homeserver, instead of relying on a `login_methods` configuration option

### ISSUE THREAD

**Issue by psrpinto** [Automattic/chatrix#43]
Currently chatrix does not retrieve the available authentication methods from the homeserver. When we introduced SSO login, we added the `login_methods` configuration option, but I think that was probably not the way to go.

Instead, I think chatrix should retrieve the available authentication methods from the homeserver, and the `login_methods` configuration option should be phased out.

**Comment by akirk** [comment]
Moving it to Future for now since eventually (naturally) we'll get to this, it's just lower priority for now.

**Comment by psrpinto** [comment]
Fixed since we've moved to using hydrogen instead of chatterbox.
