### ISSUE TITLE
Sending a message does not automatically scroll to it in the timeline

### ISSUE THREAD

**Issue by psrpinto** [Automattic/chatrix#82]
At least on firefox, possibly on other browsers as well.

![chatrix-scrolling](https://user-images.githubusercontent.com/550401/197760136-1d3295a1-dbff-43fe-85f4-0e86c28185cd.gif)

**Comment by akirk** [comment]
![hydrogen-scrolling](https://user-images.githubusercontent.com/203408/197770834-22641aed-4a00-436f-ae8a-8781299b90f3.gif)

**Comment by akirk** [comment]
Maybe Chatterbox has a solution for this, @psrpinto will research that in order to move this issue forward.

**Comment by psrpinto** [comment]
This appears to be fixed in the latest version of Firefox. Will re-open if the issue resurfaces.
