### ISSUE TITLE
Screen to create a room cannot be closed

### ISSUE THREAD

**Issue by psrpinto** [Automattic/chatrix#89]
If user gets to this screen, the only way out of it is to delete local storage.

<img width="655" alt="Screenshot 2022-10-27 at 14 59 44" src="https://user-images.githubusercontent.com/550401/198305826-a2471677-23d6-47dd-9e5a-aafdd2dfafcd.png">

**Comment by psrpinto** [comment]
Opened PR against hydrogen: https://github.com/vector-im/hydrogen-web/pull/951

**Comment by ashfame** [comment]
This now works because of using our fork as hydrogen dependency, so closing.
