### ISSUE TITLE
Should we use single-room mode for the alpha test?

### ISSUE THREAD

**Issue by psrpinto** [Automattic/chatrix#90]
Single room mode is when user only has access to a single room, and cannot see the list of rooms.

If we decide to use single-room mode, I've created https://orbit-sandbox.element.io/#/room/#chatrix:orbit-sandbox.ems.host for this purpose.

**Comment by psrpinto** [comment]
@akirk @ashfame

**Comment by ashfame** [comment]
I think, for now, single room mode is the way to go. Otherwise it might feel like a big application that's embedded, rather than a part of the page itself.

Eventually, I think we want to stick to the appeal of making it feel like its a part of any page, its loaded on.

**Comment by psrpinto** [comment]
Ok, closing this as there is no action to be taken at this point.
